[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tale"
version = "0.1.0"
description = "Skynet-Lite: Lean Autonomous Agent Architecture"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    # MCP and async
    "mcp>=1.0.0",
    "asyncio-mqtt",
    "aiohttp",

    # Model management
    "ollama",
    "openai>=1.0.0",
    "anthropic",

    # Data and storage
    "pydantic>=2.0.0",
    "sqlalchemy>=2.0.0",

    # CLI and TUI
    "click>=8.0.0",
    "rich>=13.0.0",
    "textual>=0.40.0",

    # Utilities
    "python-dotenv",
    "gitpython",
    "sentence-transformers",
    "numpy",
    "scikit-learn",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio",
    "pytest-cov",
    "black",
    "ruff",
    "mypy",
    "pre-commit",
]

[project.scripts]
tale = "tale.cli.main:main"

[tool.black]
line-length = 88
target-version = ['py39']

[tool.ruff]
line-length = 88
target-version = "py39"
select = ["E", "F", "I", "N", "W", "UP"]
ignore = ["E501"]  # Line too long (handled by black)

[tool.ruff.isort]
known-first-party = ["tale"]

[tool.mypy]
python_version = "3.9"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--strict-markers --strict-config --cov=tale"
